### ISSUE TITLE
Add build command for Linux

### ISSUE THREAD

**Issue by nahuakang** [gustavopezzi/voxelspace#1]
Hey Gustavo, just tried using this repo and found that the `make build` command might not work on Linux. Could you please add a comment for the following?

```
build:
  gcc voxel.c dos/*.c `sdl2-config --libs --cflags` -lGLEW -lglfw -lGL -lm -lpthread -o voxel
```

Took me a while to figure out since I'm that bad student who rarely finishes a course thus never learned how to write `Makefile` properly :sweat_smile:

**Comment by gustavopezzi** [comment]
Hi there!
I think this command should work as well for Linux, but you might need to install a couple of dependencies before.
Check out the Linux [installation tips](https://github.com/mattiasgustavsson/dos-like#linux) from the dos-like repository.
These are the main ones:
`sudo apt-get install libsdl2-dev`
`sudo apt-get install libglew-dev`
I hope this helps.
